version: '3.7'
services:
  snedvigimost-prod:
    container_name: snedvigimost-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
      - '2015:2015'
      - '2019:2019'
